# -*- coding: utf-8 -*-
"""CC2 STORY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KuT4LUQIM5rZ3rJe2SLNt6vo1w3R8QAs
"""

print("Hello, Girlypop <3")

#Welcome Page

print("Welcome to The Escape!")
user_options = ('1', '2', '3')

while True:
    print()
    print("MENU")
    print('[1] Start Game')
    print('[2] Credits')
    print('[3] Quit')

    print()
    user_input = input("Enter an option: ")

    if user_input in user_options:
        break
    else:
        print()
        print("Option Invalid")

#Scene 1
if user_input  == '1':
    print("Year 854.")
    print("""Peace has reigned in the heavens and the Earth after 2000 long years of war between angels and devils.
          It was peaceful they said, where laughter of children rang, and songs of glory were sung in choirs.
          The grass dances with the wind, the birds sing songs of freedom, everything is peaceful.
          The cry of a new born baby sounded across the small village.
          “IT’S A BOY!” announced by the physician, and everyone clapped and exclaimed their excitement.
          A new baby boy was born, not a royal, nor divine, but every birth is celebrated as a baby symbolizes a new hope.
          Everyone cheered and celebrated, tears of joy were raining, and everyone was just enormously grateful.
          The family was showered with love and support. Everything is peaceful.  But one shouldn’t be blinded by the beauty of it all. """)
    print("========================================================================================================================")
    print("Year 875")
    print("""Eljin had just celebrated his 21st birthday, and his only wish was to explore the world beyond the village’s borders.
          His parents were worried, of course. No one has ever set foot outside the village, no one dared to see the outside world.
          But his courage, and his love for adventures urged him to go forward, and explore more than any human has explored.
          After weeks of searching for the unknown, he has finally stumbled upon the deep dark forest. The only problem is, where should he head to? """)
    eljin_forest_option = ('1','2')

    while True:
        print('[1] Forest on the right where bats and spider webs covered the pavement.')
        print('[2] Forest on the left where water was traveling, and unknown creatures are hiding in the waters.')

        print()
        eljin_forest_choice = input("Where will Eljin head to? ")
        if eljin_forest_choice in eljin_forest_option:
            break
        else:
            print("Oh no! There's no such thing!")

#Credits
if user_input == '2':
    print("The geniuses behind The Escape!")
    print()
    print("GIRLY POP!")
    print()
    print("Lucci Ania Luisse Fagela")
    print("Rupert Xavier Galera")
    print("Jenny Ann Guyong")
    print("Princess Joy Vidad")

#Quit
if user_input == '3':
    print("Thank you for playing The Escape!")
    print("Quote dito huehuehue")

#hi babes, tweaked the code a bit and put them in each function para madaling matawag if magcchange na ng scene

import time

def startGame():
    print("""
    -->> MENU <<--
    [1] Start Game
    [2] Credits
    [3] Quit""")

    print()

    user_input = input("Enter an option: ")

    if user_input == '1':
        scene1()
    elif user_input == '2':
        credits()
    elif user_input == '3':
        global isPlaying #makes isPlaying accessible inside this function

        print("\nThank you for playing The Escape!")
        print("Quote dito huehuehue")

        isPlaying = False
    else: #if player entered a number other than 1, 2, or 3
        print("\nOption Invalid!")

#run niyo sa vs code, mas smooth
#dami nang lines bcos of this huahua tho this is not necessary naman, for visuals lang so we can omit this if ever

def scene1():
    print("\n========================================================================================================================")
    print()

    line1 = "Year 854.\n" #since the end parameter is an empty string and not \n anymore, we need that \n to display line 2 to the next line
    for char in line1:
        print(char, end='')
        #this loops through each of line1's characters and prints them without adding any new line in between, that's why the end parameter is empty
        time.sleep(.05)
        #each character gets printed with 0.5 secs delay in between

    time.sleep(1)
    print()

    line2 = """Peace has reigned in the heavens and the Earth after 2000 long years of war between angels and devils.
It was peaceful they said, where laughter of children rang, and songs of glory were sung in choirs.
The grass dances with the wind, the birds sing songs of freedom, everything is peaceful.
The cry of a new born baby sounded across the small village.
“IT'S A BOY!” announced by the physician, and everyone clapped and exclaimed their excitement.
A new baby boy was born, not a royal, nor divine, but every birth is celebrated as a baby symbolizes a new hope.
Everyone cheered and celebrated, tears of joy were raining, and everyone was just enormously grateful.
The family was showered with love and support. Everything is peaceful.  But one shouldn't be blinded by the beauty of it all.\n"""
    for char in line2:
        print(char, end='')
        time.sleep(.05)

    time.sleep(1)
    print()

    line3 = "Year 875.\n"
    for char in line3:
        print(char, end='')
        time.sleep(.05)

    time.sleep(1)
    print()

    line4 = """Eljin had just celebrated his 21st birthday, and his only wish was to explore the world beyond the village's borders.
His parents were worried, of course. No one has ever set foot outside the village, no one dared to see the outside world.
But his courage, and his love for adventures urged him to go forward, and explore more than any human has explored.
After weeks of searching for the unknown, he has finally stumbled upon the deep dark forest. The only problem is...\n"""
    for char in line4:
        print(char, end='')
        time.sleep(.05)

    time.sleep(1)
    print()

    print('[1] Forest on the right where bats and spider webs covered the pavement.')
    time.sleep(1)
    print('[2] Forest on the left where water was traveling, and unknown creatures are hiding in the waters.')

    time.sleep(1)
    print()

    eljin_forest_choice = input("Where should he head to? ")

    if eljin_forest_choice == '1':
        rightForest()
    elif eljin_forest_choice == '2':
        leftForest()
    else: #if player entered a number other than 1 or 2
        print("Oh no! There's no such thing!")


def rightForest():
    hasWon = True

    #load map then fightfightfight

    if (hasWon):
        scene2() #if has won, proceed to scene 2
    else:
        scene1() #if didn't win, go back to scene1


def leftForest():
    hasWon = True

    #load map then fightfightfight

    if (hasWon):
        scene2() #if won, proceed to scene 2
    else:
        scene1() #if didn't win, go back to scene1


def scene2():
    pass


def credits():
    print("\n========================================================================================================================\n")

    time.sleep(1)
    print("The geniuses behind The Escape!")
    print()

    time.sleep(1)

    load = "..."
    for char in load:
        print(char, end='')
        time.sleep(.5)

    time.sleep(1)
    print("GIRLY POP!")
    print()

    time.sleep(1)

    print("Lucci Ania Luisse Fagela")
    time.sleep(1)
    print("Rupert Xavier Galera")
    time.sleep(1)
    print("Jenny Ann Guyong")
    time.sleep(1)
    print("Princess Joy Vidad")


#while isPlaying is True, the program or the game will continue to run and will be terminated when it is set to False perhaps when player wants to quit or when they lose?
#btw should we give them the option to quit while in game?

isPlaying = True
while isPlaying:
    print("\n========================================================================================================================\n")
    print("Welcome to The Escape!")
    startGame()
